require('./models/index');
const express = require('express');
const app = express();
const post = express.Router();
const author = express.Router();
const postRouter = require("./route/post")(post);
const authorRouter = require("./route/author")(author);
const bodyParser = require("body-parser");
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use("/post",postRouter);
app.use("/author",authorRouter);
app.listen(3000);
