require('./models/index');
const express = require('express');
const app = express();
const post = express.Router();
const author = express.Router();
const cors =require ('cors');
const postRouter = require("./routes/post")(post);
const authorRouter = require("./routes/author")(author);
const bodyParser = require("body-parser");
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use("/post",postRouter);
app.use("/author",authorRouter);
app.listen(5000);
